/**
 * All Effect oxlint rules, exported by rule name for Plugin.define.
 *
 * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
 */

// --- API bans ---
export { noEffectBind } from "./no-effect-bind.js";
export { noEffectDo } from "./no-effect-do.js";

// --- AST pattern rules ---
export { noAs } from "./no-as.js";
export { noAsyncFunction } from "./no-async-function.js";
export { noChainedTypeAssertions } from "./no-chained-type-assertions.js";
export { noConditionalEmptyObjectSpread } from "./no-conditional-empty-object-spread.js";
export { noDynamicImports } from "./no-dynamic-imports.js";
export { noGlobals } from "./no-globals.js";
export { noKnownValueWidening } from "./no-known-value-widening.js";
export { noModuleMocks } from "./no-module-mocks.js";
export { noNewError } from "./no-new-error.js";
export { noNewPromise } from "./no-new-promise.js";
export { noNodeBuiltinImport } from "./no-node-builtin-import.js";
export { noNullish } from "./no-nullish.js";
export { noObjectParameters } from "./no-object-parameters.js";
export { noRuntimeTypeof } from "./no-runtime-typeof.js";
export { noShapeInSymbolNames } from "./no-shape-in-symbol-names.js";
export { noTernary } from "./no-ternary.js";
export { noTestLifecycleHooks } from "./no-test-lifecycle-hooks.js";
export { noThrowStatement } from "./no-throw-statement.js";
export { noTryCatch } from "./no-try-catch.js";
export { noUnknownParameters } from "./no-unknown-parameters.js";
export { noUnknownTypeAliases } from "./no-unknown-type-aliases.js";
export { noUnsafeDictionaryType } from "./no-unsafe-dictionary-type.js";
export { noWidenThenAssert } from "./no-widen-then-assert.js";
export { preferCatchTag } from "./prefer-catch-tag.js";
export { preferEffectFn } from "./prefer-effect-fn.js";
export { preferMatchTagsExhaustive } from "./prefer-match-tags-exhaustive.js";
export { preferPredicateIsTagged } from "./prefer-predicate-is-tagged.js";
