/**
 * All Effect oxlint rules for Plugin.define. Each rule module exports only its rule, named by rule id.
 *
 * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
 */

// --- API bans ---
export * from "./no-effect-bind.js";
export * from "./no-effect-do.js";

// --- AST pattern rules ---
export * from "./max-cognitive-complexity.js";
export * from "./max-halstead-difficulty.js";
export * from "./no-alias-test-layer.js";
export * from "./no-array-filter-map.js";
export * from "./no-as.js";
export * from "./no-async-function.js";
export * from "./no-chained-type-assertions.js";
export * from "./no-conditional-empty-object-spread.js";
export * from "./no-dynamic-imports.js";
export * from "./no-eager-acquire.js";
export * from "./no-effect-bun-test-it-call.js";
export * from "./no-effect-run-in-tests.js";
export * from "./no-fixed-wait-in-tests.js";
export * from "./no-globals.js";
export * from "./no-inline-provide.js";
export * from "./no-known-value-widening.js";
export * from "./no-lint-evasion.js";
export * from "./no-managed-runtime-in-effect.js";
export * from "./no-module-level-mutable-state.js";
export * from "./no-module-mocks.js";
export * from "./no-nested-effect-gen.js";
export * from "./no-new-error.js";
export * from "./no-new-promise.js";
export * from "./no-node-builtin-import.js";
export * from "./no-nullish.js";
export * from "./no-object-parameters.js";
export * from "./no-per-call-cache-construction.js";
export * from "./no-positional-log-arguments.js";
export * from "./no-promise-chains-in-tests.js";
export * from "./no-reduce-accumulator-copy.js";
export * from "./no-reflect-apply.js";
export * from "./no-reflect-get.js";
export * from "./no-run-collect-on-unbounded-stream.js";
export * from "./no-runtime-typeof.js";
export * from "./no-sequential-effect-all.js";
export * from "./no-shape-in-symbol-names.js";
export * from "./no-silent-catch-all.js";
export * from "./no-ternary.js";
export * from "./no-test-globals.js";
export * from "./no-test-lifecycle-hooks.js";
export * from "./no-throw-statement.js";
export * from "./no-try-catch.js";
export * from "./no-unbounded-concurrency.js";
export * from "./no-unbounded-retry.js";
export * from "./no-unknown-parameters.js";
export * from "./no-unknown-returns.js";
export * from "./no-unknown-type-aliases.js";
export * from "./no-unsafe-dictionary-type.js";
export * from "./no-widen-then-assert.js";
export * from "./prefer-catch-tag.js";
export * from "./prefer-effect-fn.js";
export * from "./prefer-match-tags-exhaustive.js";
export * from "./prefer-predicate-is-tagged.js";
export * from "./prefer-schema-tagged-union.js";
export * from "./prefer-service-of.js";
export * from "./require-named-effect-fn.js";
export * from "./require-suppression-reason.js";
