/**
 * All Effect oxlint rules, exported by rule name for Plugin.define.
 *
 * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
 */

// --- API bans ---
export { noEffectBind } from "./no-effect-bind.js";
export { noEffectDo } from "./no-effect-do.js";

// --- AST pattern rules ---
export { noAsyncFunction } from "./no-async-function.js";
export { noDynamicImports } from "./no-dynamic-imports.js";
export { noGlobals } from "./no-globals.js";
export { noNewError } from "./no-new-error.js";
export { noNewPromise } from "./no-new-promise.js";
export { noNodeBuiltinImport } from "./no-node-builtin-import.js";
export { noTernary } from "./no-ternary.js";
export { noThrowStatement } from "./no-throw-statement.js";
export { noTryCatch } from "./no-try-catch.js";
