/**
 * Auto-generate src/rules/index.ts barrel from rule files.
 *
 * Scans src/rules/ for rule files (ignoring _*.ts and index.ts),
 * extracts the exported const name, and writes the barrel.
 *
 * Usage: bun run scripts/codegen.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const RULES_DIR = join(import.meta.dir, "../src/rules")
const INDEX_PATH = join(RULES_DIR, "index.ts")

interface RuleEntry {
  fileName: string
  exportName: string
  category: string
}

const categoryOrder = [
  "API bans",
  "Global bans",
  "Import bans",
  "Statement bans",
  "JSON",
  "AST pattern rules",
  "Effect-context rules",
  "Other",
]

function detectCategory(content: string, fileName: string): string {
  if (content.includes("makeEffectContextTracker")) return "Effect-context rules"
  if (content.includes("Rule.banImport") || content.includes("banImport")) return "Import bans"
  if (content.includes("Rule.banStatement")) return "Statement bans"
  if (content.includes("Rule.banMember") || content.includes("Rule.banMultiple")) {
    if (fileName.includes("global") || fileName.includes("new-")) return "Global bans"
    if (fileName.includes("json")) return "JSON"
    if (fileName.includes("process")) return "Global bans"
    return "API bans"
  }
  if (content.includes("Rule.banCallOf") || content.includes("banCallOf")) {
    if (fileName.includes("global") || fileName.includes("timer")) return "Global bans"
    return "API bans"
  }
  return "AST pattern rules"
}

function extractExportName(content: string): string | null {
  const match = content.match(/export const (\w+)/)
  return match?.[1] ?? null
}

const files = readdirSync(RULES_DIR)
  .filter((f) => f.endsWith(".ts") && !f.startsWith("_") && f !== "index.ts")
  .sort()

const entries: RuleEntry[] = []

for (const file of files) {
  const content = readFileSync(join(RULES_DIR, file), "utf-8")
  const exportName = extractExportName(content)
  if (!exportName) {
    console.warn(`⚠ No export found in ${file}, skipping`)
    continue
  }
  entries.push({
    fileName: file.replace(".ts", ""),
    exportName,
    category: detectCategory(content, file),
  })
}

// Group by category
const grouped = new Map<string, RuleEntry[]>()
for (const entry of entries) {
  const list = grouped.get(entry.category) ?? []
  list.push(entry)
  grouped.set(entry.category, list)
}

// Build output
const lines: string[] = [
  '/**',
  ' * All Effect oxlint rules, exported by rule name for Plugin.define.',
  ' *',
  ' * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.',
  ' */',
  '',
]

for (const cat of categoryOrder) {
  const catEntries = grouped.get(cat)
  if (!catEntries || catEntries.length === 0) continue
  lines.push(`// --- ${cat} ---`)
  for (const entry of catEntries) {
    lines.push(`export { ${entry.exportName} } from "./${entry.fileName}.js"`)
  }
  lines.push('')
}

const output = lines.join('\n')
writeFileSync(INDEX_PATH, output)

console.log(`✓ Generated ${INDEX_PATH} with ${entries.length} rules`)
for (const [cat, catEntries] of grouped) {
  console.log(`  ${cat}: ${catEntries.length}`)
}
