/**
 * Strict, non-type-aware policy for Effect-native application code.
 *
 * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
 */
export const recommended = {
  "effect/noAs": "error",
  "effect/noAsyncFunction": "error",
  "effect/noChainedTypeAssertions": "error",
  "effect/noConditionalEmptyObjectSpread": "error",
  "effect/noDynamicImports": "error",
  "effect/noEffectBind": "error",
  "effect/noEffectDo": "error",
  "effect/noGlobals": "error",
  "effect/noKnownValueWidening": "error",
  "effect/noNewError": "error",
  "effect/noNewPromise": "error",
  "effect/noNodeBuiltinImport": "error",
  "effect/noNullish": "error",
  "effect/noObjectParameters": "error",
  "effect/noRuntimeTypeof": "error",
  "effect/noShapeInSymbolNames": "error",
  "effect/noTernary": "error",
  "effect/noTestLifecycleHooks": "error",
  "effect/noThrowStatement": "error",
  "effect/noTryCatch": "error",
  "effect/noUnknownParameters": "error",
  "effect/noUnknownTypeAliases": "error",
  "effect/noUnsafeDictionaryType": "error",
  "effect/noWidenThenAssert": "error",
  "effect/preferCatchTag": "error",
  "effect/preferEffectFn": "error",
  "effect/preferMatchTagsExhaustive": "error",
  "effect/preferPredicateIsTagged": "error",
} as const;
