/**
 * All Effect oxlint rules, exported by rule name for Plugin.define.
 *
 * AUTO-GENERATED by scripts/codegen.ts — do not edit manually.
 */

// --- API bans ---
export { noEffectAs } from "./no-effect-as.js"
export { noEffectAsync } from "./no-effect-async.js"
export { noEffectBind } from "./no-effect-bind.js"
export { noEffectDo } from "./no-effect-do.js"
export { noEffectNever } from "./no-effect-never.js"
export { noOptionAs } from "./no-option-as.js"
export { noRunInEffect } from "./no-run-in-effect.js"
export { noRuntimeRunFork } from "./no-runtime-run-fork.js"

// --- Global bans ---
export { noGlobalConsole } from "./no-global-console.js"
export { noGlobalDate } from "./no-global-date.js"
export { noGlobalFetch } from "./no-global-fetch.js"
export { noGlobalRandom } from "./no-global-random.js"
export { noGlobalTimers } from "./no-global-timers.js"
export { noProcessEnv } from "./no-process-env.js"

// --- Statement bans ---
export { noDynamicImport } from "./no-dynamic-import.js"
export { noIfStatement } from "./no-if-statement.js"
export { noSwitchStatement } from "./no-switch-statement.js"
export { noThrowStatement } from "./no-throw-statement.js"
export { noTryCatch } from "./no-try-catch.js"

// --- JSON ---
export { noJsonParse } from "./no-json-parse.js"

// --- AST pattern rules ---
export { noArrowLadder } from "./no-arrow-ladder.js"
export { noAsyncFunction } from "./no-async-function.js"
export { noEffectFnGenerator } from "./no-effect-fn-generator.js"
export { noEffectGenAdapter } from "./no-effect-gen-adapter.js"
export { noEffectMapVoid } from "./no-effect-map-void.js"
export { noEffectOrElseLadder } from "./no-effect-orElse-ladder.js"
export { noEffectSucceedString } from "./no-effect-succeed-string.js"
export { noEffectSucceedVariable } from "./no-effect-succeed-variable.js"
export { noEffectSucceedVoid } from "./no-effect-succeed-void.js"
export { noEffectSyncConsole } from "./no-effect-sync-console.js"
export { noEffectSyncWrapper } from "./no-effect-sync-wrapper.js"
export { noEffectTypeAlias } from "./no-effect-type-alias.js"
export { noEffectWrapperAlias } from "./no-effect-wrapper-alias.js"
export { noExtendsNativeError } from "./no-extends-native-error.js"
export { noFlatmapLadder } from "./no-flatmap-ladder.js"
export { noFromNullableCoalesce } from "./no-fromnullable-coalesce.js"
export { noIifeWrapper } from "./no-iife-wrapper.js"
export { noInstanceofSchema } from "./no-instanceof-schema.js"
export { noManualEffectChannels } from "./no-manual-effect-channels.js"
export { noMatchEffectBranch } from "./no-match-effect-branch.js"
export { noMatchVoidBranch } from "./no-match-void-branch.js"
export { noNestedEffectCall } from "./no-nested-effect-call.js"
export { noNestedEffectGen } from "./no-nested-effect-gen.js"
export { noNestedPipe } from "./no-nested-pipe.js"
export { noNewError } from "./no-new-error.js"
export { noNewPromise } from "./no-new-promise.js"
export { noNodeBuiltinImport } from "./no-node-builtin-import.js"
export { noOptionBooleanNormalization } from "./no-option-boolean-normalization.js"
export { noReturnInArrow } from "./no-return-in-arrow.js"
export { noReturnNull } from "./no-return-null.js"
export { noStringSentinelConst } from "./no-string-sentinel-const.js"
export { noTernary } from "./no-ternary.js"
export { noUnnecessaryArrowBlock } from "./no-unnecessary-arrow-block.js"
export { noUnnecessaryEffectGen } from "./no-unnecessary-effect-gen.js"
export { noUnnecessaryPipe } from "./no-unnecessary-pipe.js"

// --- Effect-context rules ---
export { noConsoleInEffect } from "./no-console-in-effect.js"
export { noDateInEffect } from "./no-date-in-effect.js"
export { noFetchInEffect } from "./no-fetch-in-effect.js"
export { noInlineRuntimeProvide } from "./no-inline-runtime-provide.js"
export { noJsonInEffect } from "./no-json-in-effect.js"
export { noPlatformGlobals } from "./no-platform-globals.js"
export { noProcessEnvInEffect } from "./no-process-env-in-effect.js"
export { noRandomInEffect } from "./no-random-in-effect.js"
export { noThrowInEffectGen } from "./no-throw-in-effect-gen.js"
export { noTimersInEffect } from "./no-timers-in-effect.js"
export { noTryCatchInEffectGen } from "./no-try-catch-in-effect-gen.js"
